name: demo
favicon: null
layout_spectrum: 0.676852225093171
typography_spectrum: 0.2566270879469812
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.44827771722339094
  lightness: 0.3586975699290633
  saturation: 0.4372917066793889
  rhythmicContrast: 0.633975273463875
purpose: []
