name: Blog; Carson Longhorn (Gadjet)
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19993
title: Blog; Carson Longhorn (Gadjet)
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4375
  lightness: 0.3586975699290633
  saturation: 0.4372917066793889
  rhythmicContrast: 0.633975273463875
purpose: []
content: []
github: true
url: 'http://thegrid.ai/gadjet/'
content_rating:
  adult: false
author:
  name: Carson Longhorn
  email: blogmail@unrelated.net.au
  url: 'https://longhorn.id.au'
